### ISSUE TITLE
How to use the app locally?

### ISSUE THREAD

**Issue by Jonny-T-cyber** [jarhot1992/Remote-ADB#1]
Good morning,
I also wrote an email to technical support but I have not received any response...
I bought the app and I want to "debug" locally my smartphone (a Samsung Galaxy Note10+) without root and without pc. 

Does this mean "locally" or what?
The app do this, correct? 

So... I can't use the app locally because it asks me for a "pairing code"... 

Where can I find it? 

Thanks

**Comment by jarhot1992** [comment]
Refer to https://developer.android.com/studio/command-line/adb
Default IP 127.0.0.1 and default port 5555 is local mode.

**Comment by Jonny-T-cyber** [comment]
> Do not use pairing mode! Refer to https://developer.android.com/studio/command-line/adb Default IP 127.0.0.1 and default port 5555 is local mode.

This is the site on my smartphone:
![image](https://user-images.githubusercontent.com/33354144/188322459-55a23bf7-3413-4470-8f18-587e4e5b5337.png)

"Connection refused"...
So what else should I do?

**Comment by jarhot1992** [comment]
[How to open and connect adb](https://github.com/jarhot1992/Remote-ADB/blob/main/md/tutorials.md) 
Refer to https://github.com/jarhot1992/Remote-ADB/blob/main/md/tutorials.md
Updated a few days ago.....

**Comment by Jonny-T-cyber** [comment]
> [How to open and connect adb](https://github.com/jarhot1992/Remote-ADB/blob/main/md/tutorials.md) 
> Refer to https://github.com/jarhot1992/Remote-ADB/blob/main/md/tutorials.md
> Updated a few days ago.....


Unfortunately it still doesn't work ...
What should I do?
(I remind you that I bought the app)


![Screenshot_20221105-111721_ADB.jpg](https://user-images.githubusercontent.com/33354144/200115054-c9a66ea3-0819-4a42-8e06-548871d81535.jpg)

**Comment by Erz3** [comment]
I have got the same problem with Android 11.

**Comment by guzelonur** [comment]
Same problem with Android 13. Using Samsung Galaxy M23. It always says connection refused. What can we do?
