### ISSUE TITLE
https://github.com/jarhot1992/Remote-ADB/blob/main/image/connectADB4x_13/1.jpeg


### ISSUE THREAD

**Issue by Cabo4200** [jarhot1992/Remote-ADB#11]

**Comment by Bobby100911** [comment]
Remove smart rat switch

**Comment by noejaun** [comment]
Hmm

**Comment by Heydude13** [comment]
[]()![img_17_1685858020192.jpg](https://github.com/jarhot1992/Remote-ADB/assets/135498613/60b38be2-9074-4bd8-a6c9-37823d1bf3b6)
