### ISSUE TITLE
add par  120.020.555:5555


### ISSUE THREAD

**Issue by Akafm15** [jarhot1992/Remote-ADB#38]
Powered by ADB-Local&Remote ADB Shell,
Download url https://play.google.com/store/apps/details?id=com.github.standardadb
adb pair 120.020.555:5555
* daemon not running; starting now at tcp:5037
ADB server didn't ACK
Full server startup log: /data/user/0/com.github.standardadb/cache/adb.10469.log
Server had pid: 5148
--- adb starting (pid 5148) ---
adb I 05-08 15:28:38  5148  5148 main.cpp:63] Android Debug Bridge version 1.0.41
adb I 05-08 15:28:38  5148  5148 main.cpp:63] Version 31.0.3p1-android-tools
adb I 05-08 15:28:38  5148  5148 main.cpp:63] Installed as /data/app/~~THUWhXF7s6IpWJO5OT5cTg==/com.github.standardadb-7O2hlxbxBwcCWlNVhdPL6Q==/lib/arm64/libfs64.so
adb I 05-08 15:28:38  5148  5148 main.cpp:63] 
adb F 05-08 15:28:38  5148  5148 main.cpp:155] could not install *smartsocket* listener: Address already in use

* failed to start daemon
error: cannot connect to daemon
Enter pairing code: 
5555
* daemon not running; starting now at tcp:5037
ADB server didn't ACK
Full server startup log: /data/user/0/com.github.standardadb/cache/adb.10469.log
Server had pid: 5196
--- adb starting (pid 5196) ---
adb I 05-08 15:28:42  5196  5196 main.cpp:63] Android Debug Bridge version 1.0.41
adb I 05-08 15:28:42  5196  5196 main.cpp:63] Version 31.0.3p1-android-tools
adb I 05-08 15:28:42  5196  5196 main.cpp:63] Installed as /data/app/~~THUWhXF7s6IpWJO5OT5cTg==/com.github.standardadb-7O2hlxbxBwcCWlNVhdPL6Q==/lib/arm64/libfs64.so
adb I 05-08 15:28:42  5196  5196 main.cpp:63] 
adb F 05-08 15:28:43  5196  5196 main.cpp:155] could not install *smartsocket* listener: Address already in use

* failed to start daemon
error: cannot connect to daemon

['|pull: *smartsocket*|']
sh: <stdin>[8]: [|pull: *smartsocket*|]: inaccessible or not found
<----------------------------------------------------
---------------------------------------------------->
pull request
sh: <stdin>[10]: pull: inaccessible or not found
/storage/emulated/0
<----------------------------------------------------
0   <kml xmlns="http://www.opengis.net/kml/2.2">
1   213.207.186.75
2   android-ndk-announce@googlegroups.com
3   sdkmanager "platform-tools" "platforms;android-33"
4   14
5   adb devices
6   adb connect 120.020.5555:5555
7   adb connect 120.020.5555:40954095
8   1
9   adb connect 120.020.555:5555
10   5555
11   adb pair 120.020.555:5555
12   5555
13   ['|pull: *smartsocket*|']
14   pull request
---------------------------------------------------->
3
sh: <stdin>[12]: 3: inaccessible or not found
 ''platform-tools"

\ 

add par  120.020.555:5555
add pair  120.020.555:5555
<----------------------------------------------------
0   adb devices
1   adb connect 120.020.5555:5555
2   adb connect 120.020.5555:40954095
3   1
4   adb connect 120.020.555:5555
5   5555
6   adb pair 120.020.555:5555
7   5555
8   ['|pull: *smartsocket*|']
9   pull request
10   3
11   ''platform-tools"
12   \
13   add par  120.020.555:5555
14   add pair  120.020.555:5555
---------------------------------------------------->
14
8
fix-1409-add-channelmask

{
    "best_target_priority": 1,
    "bid": "10084135",
    "branch": "aosp-master-ndk",
    "branch_priority": 1,
    "build_configs": {},
    "build_dependencies": [],
    "build_type": "submitted",
    "dependency_targets": [],
    "device_dir": "/buildbot/src/android/master-ndk",
    "docker_image": null,
    "enable_docker": true,
    "git-pull": null,
    "git-server": "https://android.googlesource.com",
    "hostname": "abfarm-2004-1100",
    "inc-build": false,
    "java-version": "1.7",
    "last_logfile": null,
    "out_dir": "/buildbot/src/android/master-ndk/out",
    "parsed_manifest": {
        "parsedDefault": {
            "remote": "aosp",
            "revision": "master",
            "syncJ": "4"
        },
        "projects": [
            {
                "groups": [
                    "presubmit"
                ],
                "name": "platform/bionic",
                "path": "bionic",
                "remote": {
                    "fetch": "https://android.googlesource.com/",
                    "name": "aosp",
                    "review": "https://android.googlesource.com/"
                },
                "revision": "aaaf46837009d228531c78836823e5c42e15691b"
            },
            {
                "groups": [
                    "presubmit"
                ],
                "name": "platform/development",
                "path": "development",
                "remote": {
                    "fetch": "https://android.googlesource.com/",
                    "name": "aosp",
                    "review": "https://android.googlesource.com/"
                },
                "revision": "9af471898448c180eee89bcda114d0db4359db30"
            },
            {
                "name": "platform/external/effcee",
                "path": "external/effcee",
                "remote": {
                    "fetch": "https://android.googlesource.com/",
                    "name": "aosp",
                    "review": "https://android.googlesource.com/"
                },
                "revision": 
<----------------------------------------------------
0   adb connect 120.020.555:5555
1   5555
2   adb pair 120.020.555:5555
3   5555
4   ['|pull: *smartsocket*|']
5   pull request
6   3
7   ''platform-tools"
8   \
9   add par  120.020.555:5555
10   add pair  120.020.555:5555
11   14
12   8
13   fix-1409-add-channelmask
14   {
    "best_target_priority": 1,
    "bid": "10084135",
    "branch": "aosp-master-ndk",
    "branch_priority": 1,
    "build_configs": {},
    "build_dependencies": [],
    "build_type": "submitted",
    "dependency_targets": [],
    "device_dir": "/buildbot/src/android/master-ndk",
    "docker_image": null,
    "enable_docker": true,
    "git-pull": null,
    "git-server": "https://android.googlesource.com",
    "hostname": "abfarm-2004-1100",
    "inc-build": false,
    "java-version": "1.7",
    "last_logfile": null,
    "out_dir": "/buildbot/src/android/master-ndk/out",
    "parsed_manifest": {
        "parsedDefault": {
            "remote": "aosp",
            "revision": "master",
            "syncJ": "4"
        },
        "projects": [
            {
                "groups": [
                    "presubmit"
                ],
                "name": "platform/bionic",
                "path": "bionic",
                "remote": {
                    "fetch": "https://android.googlesource.com/",
                    "name": "aosp",
                    "review": "https://android.googlesource.com/"
                },
                "revision": "aaaf46837009d228531c78836823e5c42e15691b"
            },
            {
                "groups": [
                    "presubmit"
                ],
                "name": "platform/development",
                "path": "development",
                "remote": {
                    "fetch": "https://android.googlesource.com/",
                    "name": "aosp",
                    "review": "https://android.googlesource.com/"
                },
                "revision": "9af471898448c180eee89bcda114d0db4359db30"
            },
            {
                "name": "platform/external/effcee",
                "path": "external/effcee",
                "remote": {
                    "fetch": "https://android.googlesource.com/",
                    "name": "aosp",
                    "review": "https://android.googlesource.com/"
                },
                "revision":
---------------------------------------------------->

**Comment by jarhot1992** [comment]
Please update to the latest version. The  issue has been fixed.
