### ISSUE TITLE
Is it bug? the toolkit cannot be initialized.

### ISSUE THREAD

**Issue by SONGjiemo** [jarhot1992/Remote-ADB#4]
![1DD8D2D9-8795-4245-AF67-07F2F3086F36](https://user-images.githubusercontent.com/46627639/216885831-26c8585b-4797-4e90-9e33-2e9c331b47b3.jpeg)
Always "initialize" the tool. 
I don't know why it keeps like this. 
Hoping to solve the problem,

**Comment by Lektony9** [comment]
Ssw zee```

```

**Comment by jarhot1992** [comment]
The issue has been fixed, please update to the latest version.
