### ISSUE TITLE
Pair button ALWAYS brings up Android "App Info" instead of pairing UI?! 

### ISSUE THREAD

**Issue by MrPeteH** [jarhot1992/Remote-ADB#58]
Samsung Note20 Ultra 5G. Latest Android 13 release. Nothing funny.
New install. No matter what, pressing Pair button goes directly to App Info for this app. What am I missing?

**Comment by phoover-git** [comment]
Same problem on Pixel 4a running stock Android 13.

**Comment by Red-Baran** [comment]
Same with the galaxy s20 ultra and the pro edition of the app

**Comment by Red-Baran** [comment]
I downgraded to 3.2.3 and got the proper prompt

**Comment by jarhot1992** [comment]
Please update to the latest version. The issue has been fixed.
