### ISSUE TITLE
Does this app allow you to use this ADB shell on your phone without a computer

### ISSUE THREAD

**Issue by DisputedHeart** [jarhot1992/Remote-ADB#76]
How do I get this to work on my phone without having to have a computer I just want to uninstall Facebook it's a pre-installed app and I would like to uninstall it but I can't seem to figure out how to get this to work I've tried to default IP address and Port 5555 and I'm thinking that's if it's on a Wi-Fi network and I do the wireless pairing I can get it to work if I do that but I don't know what the pairing code is but then again I'm not on a Wi-Fi network I don't have a router at all I'm just using my mobile data also looked under about phone and got my IP address and tried that in Port 555 and Port 5037 didn't work either please help thank you

**Comment by jarhot1992** [comment]
Please refer to https://github.com/jarhot1992/Remote-ADB/blob/main/md/tutorials.md#i-dont-have-a-pc-how-can-i-use-this-application-locally
