### ISSUE TITLE
Zach I

### ISSUE THREAD

**Issue by Bobby1128787** [jarhot1992/Remote-ADB#77]

**Comment by DisputedHeart** [comment]
Great answer you'll go not far

**Comment by DisputedHeart** [comment]
I did not reply to this I did not write that I asked a question I think it's number 76 and then all the sudden my name is used to insult someone I just want you to know that I did not insult you I don't have any idea why someone would insult you using my name I haven't a clue what I'm doing on here I'm just trying to learn and I know better than go around insulting people just hope you see this.

**Comment by mozzarella06** [comment]
> _No description provided._

**Comment by DisputedHeart** [comment]
No description provided how is that an answer I expect an in-depth thousand
word essay come on man for free right now , nah I appreciate it
