### ISSUE TITLE
[Help] Bought professional edition to remove ads then you removed app from play store once and you moved app as shareware completely, how do I refund or upgrade to new one without paying?

### ISSUE THREAD

**Issue by roflsunriz** [jarhot1992/Remote-ADB#93]
Title says all. Help.
![Screenshot_20230627-040646](https://github.com/jarhot1992/Remote-ADB/assets/8847851/79e2345b-909e-4ceb-91d8-dc0f3a51784b)
![Screenshot_20230627-040619](https://github.com/jarhot1992/Remote-ADB/assets/8847851/7c5d3376-af0b-4606-8234-63137bcc7fde)
![Screenshot_20230627-040659](https://github.com/jarhot1992/Remote-ADB/assets/8847851/c7429cf7-aef7-4a9e-9740-c5a8ed6ac46c)
![Screenshot_20230627-041123](https://github.com/jarhot1992/Remote-ADB/assets/8847851/412e9b71-8d96-4735-b90f-76a2b06b0f3f)

**Comment by jarhot1992** [comment]
諸事情により一時的に棚から外されておりますが、3日程度で再び棚に並ぶ予定です。

**Comment by roflsunriz** [comment]
わかりました。。取り敢えず少し待ってみます。

**Comment by roflsunriz** [comment]
戻ってきたのを確認しました。
